name: Torrent Generation

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Specify tag to run on'
        required: true
        default: 'master'
  
jobs:
  torrent:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout with ref
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Create torrents
        uses: devopsx/action-torrent@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            raspap-bookworm-arm64-lite-*.img.zip
            raspap-bookworm-armhf-lite-*.img.zip

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: torrents/*.torrent
